### ISSUE TITLE
pip install error of latests version 1.0.3

### ISSUE THREAD

**Issue by singjc** [Roestlab/dia-pasef#40]
Automated build and push of version 1.0.3 seems to fail during pip install

```
$ pip install diapysef
Collecting diapysef
  Downloading diapysef-1.0.3.tar.gz (697 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 697.7/697.7 kB 6.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6etgn60b/diapysef_28657bc4376c4d70b8640a95b96094da/setup.py", line 13, in <module>
          long_description=readme(),
        File "/tmp/pip-install-6etgn60b/diapysef_28657bc4376c4d70b8640a95b96094da/setup.py", line 4, in readme
          with open('PYPI_README.rst') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'PYPI_README.rst'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by singjc** [comment]
Fixed by reaning MANIFEST.rst to MANIFEST.in and including PYPI_README.rst in MANIFEST.
